import 'dart:convert';
import 'dart:io';

import 'package:genuineci_cli/src/commands/sync/generate_workspace_paths.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('generateWorkspacePathsSource', () {
    test('generates a static constant without initialization or imports', () {
      expect(generateWorkspacePathsSource({'dashboard': 'apps/dashboard'}), '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI
// dart format off

/// Paths relative to the repository root.
abstract final class WorkspacePaths {
  static const String dashboard = "apps/dashboard";
}
''');
    });

    test('generates an empty class for zero packages', () {
      final source = generateWorkspacePathsSource({});

      expect(source, contains('abstract final class WorkspacePaths {}'));
      expect(source, isNot(contains('import ')));
    });
  });

  group('workspacePackageNameToField', () {
    const cases = {
      'dashboard': 'dashboard',
      'build_job_worker': 'buildJobWorker',
      'genuine_ci': 'genuineCi',
      'genuine_ci_workflows': 'genuineCiWorkflows',
      'v2_api': 'v2Api',
      'build__job_worker': 'buildJobWorker',
    };
    for (final entry in cases.entries) {
      test('converts ${entry.key} to ${entry.value}', () {
        expect(workspacePackageNameToField(entry.key), entry.value);
      });
    }

    for (final name in [
      '',
      '_private',
      '2dashboard',
      'Dashboard',
      'build-job',
      'my app',
      'dashboard\n',
      'class',
      'null',
      'hash_code',
      'to_string',
      'runtime_type',
      'no_such_method',
    ]) {
      test('rejects unusable field name ${jsonEncode(name)}', () {
        expect(
          () => workspacePackageNameToField(name),
          throwsA(
            isA<FormatException>().having(
              (error) => error.message,
              'message',
              contains(jsonEncode(name)),
            ),
          ),
        );
      });
    }
  });

  group('validateWorkspacePath', () {
    for (final path in [
      'apps/dashboard',
      'packages/my app',
      '.',
      './apps/app',
    ]) {
      test('accepts repository-relative path $path', () {
        expect(() => validateWorkspacePath(path), returnsNormally);
      });
    }

    for (final path in [
      '',
      '/tmp/workspace/apps/dashboard',
      'C:/workspace/apps/dashboard',
      r'C:\workspace\apps\dashboard',
      'C:apps/dashboard',
      r'\\server\share\dashboard',
      r'\apps\dashboard',
      '../dashboard',
      'apps/../dashboard',
      r'apps\..\dashboard',
      'apps/\u0000dashboard',
    ]) {
      test('rejects invalid path ${jsonEncode(path)}', () {
        expect(
          () => validateWorkspacePath(path),
          throwsA(
            isA<FormatException>().having(
              (error) => error.message,
              'message',
              contains(jsonEncode(path)),
            ),
          ),
        );
      });
    }
  });

  group('generateWorkspacePaths', () {
    test(
      'uses package names to distinguish directories with the same name',
      () {
        final source = generateWorkspacePaths({
          'genuine_ci_workflows': 'genuine_ci',
          'genuine_ci': 'packages/genuine_ci',
        });

        expect(source, contains('genuineCi = "packages/genuine_ci";'));
        expect(source, contains('genuineCiWorkflows = "genuine_ci";'));
      },
    );

    test('sorts packages for deterministic output', () {
      final first = generateWorkspacePaths({
        'dashboard': 'apps/dashboard',
        'build_job_worker': 'apps/build_job_worker',
      });
      final second = generateWorkspacePaths({
        'build_job_worker': 'apps/build_job_worker',
        'dashboard': 'apps/dashboard',
      });

      expect(first, second);
      expect(
        first.indexOf('buildJobWorker'),
        lessThan(first.indexOf('dashboard')),
      );
    });

    test('rejects field collisions instead of overwriting a path', () {
      expect(
        () => generateWorkspacePaths({
          'build_job_worker': 'apps/worker',
          'build__job_worker': 'packages/worker',
        }),
        throwsA(
          isA<FormatException>().having(
            (error) => error.message,
            'message',
            allOf(
              contains('"build_job_worker"'),
              contains('"build__job_worker"'),
              contains('WorkspacePaths.buildJobWorker'),
            ),
          ),
        ),
      );
    });

    test('validates package names and paths before generating source', () {
      expect(
        () => generateWorkspacePaths({'class': 'apps/dashboard'}),
        throwsFormatException,
      );
      expect(
        () => generateWorkspacePaths({'dashboard': '/tmp/workspace'}),
        throwsFormatException,
      );
    });
  });

  group('generated Dart code', () {
    late Directory directory;
    late File definitions;
    late File probe;

    setUp(() async {
      directory = await Directory.systemTemp.createTemp('genuineci-path-code-');
      definitions = File(p.join(directory.path, 'paths.g.dart'));
      probe = File(p.join(directory.path, 'probe.dart'));
    });

    tearDown(() => directory.delete(recursive: true));

    Future<ProcessResult> runProbe({String? workingDirectory}) => Process.run(
      'dart',
      [probe.path],
      workingDirectory: workingDirectory,
      environment: {'PATH': Platform.environment['PATH']!},
      includeParentEnvironment: false,
    );

    test(
      'compiles constants and preserves special characters literally',
      () async {
        const paths = {
          'dashboard': 'apps/dashboard',
          'build_job_worker': 'apps/build_job_worker',
          'special':
              r'''apps/$team/${member}/"double"/'single'/back\slash'''
              '\n\r\t\b\f',
        };
        await definitions.writeAsString(generateWorkspacePaths(paths));
        await probe.writeAsString('''
import 'dart:convert';
import 'paths.g.dart';

void main() {
  const paths = [
    WorkspacePaths.dashboard,
    WorkspacePaths.buildJobWorker,
    WorkspacePaths.special,
  ];
  print(jsonEncode(paths));
}
''');

        final result = await runProbe();

        expect(result.exitCode, 0, reason: result.stderr.toString());
        expect(jsonDecode(result.stdout as String), paths.values.toList());
      },
    );

    test(
      'resolves paths from each checkout without embedding its location',
      () async {
        await definitions.writeAsString(
          generateWorkspacePaths({'dashboard': 'apps/dashboard'}),
        );
        await probe.writeAsString('''
import 'dart:io';
import 'paths.g.dart';

void main() {
  print(File(WorkspacePaths.dashboard + '/marker.txt').readAsStringSync());
}
''');

        for (final checkout in ['first', 'second']) {
          final root = p.join(directory.path, checkout);
          final marker = File(p.join(root, 'apps', 'dashboard', 'marker.txt'));
          await marker.parent.create(recursive: true);
          await marker.writeAsString(checkout);

          final result = await runProbe(workingDirectory: root);

          expect(result.exitCode, 0, reason: result.stderr.toString());
          expect(result.stdout, '$checkout\n');
        }
      },
    );

    test('compiles an empty workspace', () async {
      await definitions.writeAsString(generateWorkspacePaths({}));
      await probe.writeAsString(
        "import 'paths.g.dart';\nvoid main() => print(WorkspacePaths);\n",
      );

      final result = await runProbe();

      expect(result.exitCode, 0, reason: result.stderr.toString());
      expect(result.stdout, 'WorkspacePaths\n');
    });
  });
}
