import 'dart:convert';
import 'dart:io';

import 'package:genuineci_cli/src/commands/sync/generate_secret_definitions.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('generateSecretSource', () {
    test('generates a getter with its original environment name', () {
      expect(generateSecretSource({'ascKey': 'ASC_KEY'}), '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI (`genuineci sync secrets`)
// dart format off

import 'dart:io';

/// Provides type-safe access to Genuine CI secrets via environment variables.
abstract final class Secrets {
  /// Secret key: `ASC_KEY`
  static String get ascKey =>
      Platform.environment['ASC_KEY'] ??
      (throw StateError("Secret 'ASC_KEY' is not set in environment."));
}
''');
    });

    test(
      'emits an empty class without an unused dart:io import for zero secrets',
      () {
        final source = generateSecretSource({});

        expect(source, contains('abstract final class Secrets {}'));
        expect(source, isNot(contains('import ')));
        expect(source, isNot(contains('static String get')));
      },
    );
  });

  group('validateSecretName', () {
    for (final name in ['A', 'ascKey', 'ASC_KEY_2', '_KEY', 'CLASS', '___']) {
      test('accepts valid environment name $name', () {
        expect(() => validateSecretName(name), returnsNormally);
      });
    }

    for (final name in [
      '',
      ' ',
      '1KEY',
      'MY-KEY',
      'A B',
      'KEY\n',
      "KEY'",
      r'KEY$',
    ]) {
      test('rejects invalid environment name ${jsonEncode(name)}', () {
        expect(
          () => validateSecretName(name),
          throwsA(
            isA<FormatException>().having(
              (error) => error.message,
              'message',
              contains(jsonEncode(name)),
            ),
          ),
        );
      });
    }
  });

  group('secretNameToGetter', () {
    const cases = {
      'A': 'a',
      'ASC_KEY': 'ascKey',
      'FIREBASE_OPTIONS': 'firebaseOptions',
      'custom_SIGNING_KEY': 'customSigningKey',
      'alreadyCamelCase': 'alreadyCamelCase',
      'APIKey': 'apiKey',
      'V2_TOKEN': 'v2Token',
      '__OTHER__KEY': 'otherKey',
    };
    for (final entry in cases.entries) {
      test('converts ${entry.key} to ${entry.value}', () {
        expect(secretNameToGetter(entry.key), entry.value);
      });
    }

    for (final name in [
      '___',
      '_2FA',
      'CLASS',
      'NULL',
      'HASH_CODE',
      'TO_STRING',
      'runtimeType',
      'NO_SUCH_METHOD',
    ]) {
      test('rejects unusable Dart getter for $name', () {
        expect(() => secretNameToGetter(name), throwsFormatException);
      });
    }
  });

  group('generateSecretDefinitions', () {
    test('connects name conversion to source generation', () {
      final source = generateSecretDefinitions(['ASC_KEY']);

      expect(source, contains('static String get ascKey =>'));
      expect(source, contains("Platform.environment['ASC_KEY']"));
    });

    test('sorts and deduplicates names for deterministic output', () {
      final first = generateSecretDefinitions(['ZULU', 'ASC_KEY', 'ZULU']);
      final second = generateSecretDefinitions(['ASC_KEY', 'ZULU']);

      expect(first, second);
      expect(first.indexOf('get ascKey'), lessThan(first.indexOf('get zulu')));
    });

    test('rejects invalid names before converting them', () {
      expect(
        () => generateSecretDefinitions(['KEY\n']),
        throwsA(
          isA<FormatException>().having(
            (error) => error.message,
            'message',
            contains('Invalid secret name'),
          ),
        ),
      );
    });

    test('rejects unusable getters before generating source', () {
      expect(
        () => generateSecretDefinitions(['CLASS']),
        throwsA(
          isA<FormatException>().having(
            (error) => error.message,
            'message',
            contains('cannot be used as a Dart getter'),
          ),
        ),
      );
    });

    for (final names in [
      ['ASC_KEY', 'ascKey'],
      ['BUILD_TOKEN', 'BUILD__TOKEN'],
      ['TOKEN', '_TOKEN'],
    ]) {
      test('rejects getter collisions for $names', () {
        expect(
          () => generateSecretDefinitions(names),
          throwsA(
            isA<FormatException>().having(
              (error) => error.message,
              'message',
              allOf(
                contains(names.first),
                contains(names.last),
                contains('both map'),
              ),
            ),
          ),
        );
      });
    }
  });

  group('generated Dart code', () {
    late Directory directory;
    late File definitions;
    late File probe;

    setUp(() async {
      directory = await Directory.systemTemp.createTemp(
        'genuineci-secret-code-',
      );
      definitions = File(p.join(directory.path, 'secrets.g.dart'));
      probe = File(p.join(directory.path, 'probe.dart'));
    });

    tearDown(() => directory.delete(recursive: true));

    Future<ProcessResult> runProbe(Map<String, String> environment) =>
        Process.run(
          'dart',
          [probe.path],
          environment: {'PATH': Platform.environment['PATH']!, ...environment},
          includeParentEnvironment: false,
        );

    test(
      'compiles camelCase getters and reads the exact environment keys',
      () async {
        const environment = {
          'ASC_KEY': 'asc-value',
          'FIREBASE_OPTIONS': 'firebase-value',
          'custom_SIGNING_KEY': 'signing-value',
          'alreadyCamelCase': 'camel-value',
          'APIKey': 'api-value',
          'V2_TOKEN': 'versioned-value',
          '__OTHER__KEY': 'underscores-value',
        };
        await definitions.writeAsString(
          generateSecretDefinitions(environment.keys),
        );
        await probe.writeAsString('''
import 'dart:convert';
import 'secrets.g.dart';

void main() {
  print(jsonEncode([
    Secrets.ascKey,
    Secrets.firebaseOptions,
    Secrets.customSigningKey,
    Secrets.alreadyCamelCase,
    Secrets.apiKey,
    Secrets.v2Token,
    Secrets.otherKey,
  ]));
}
''');

        final result = await runProbe(environment);

        expect(result.exitCode, 0, reason: result.stderr.toString());
        expect(
          jsonDecode(result.stdout as String),
          environment.values.toList(),
        );
      },
    );

    test(
      'throws a clear error when the environment variable is absent',
      () async {
        await definitions.writeAsString(generateSecretDefinitions(['ASC_KEY']));
        await probe.writeAsString('''
import 'dart:io';
import 'secrets.g.dart';

void main() {
  try {
    Secrets.ascKey;
  } on StateError catch (error) {
    stderr.writeln(error.message);
    exitCode = 2;
  }
}
''');

        final result = await runProbe({});

        expect(result.exitCode, 2);
        expect(result.stdout, isEmpty);
        expect(result.stderr, "Secret 'ASC_KEY' is not set in environment.\n");
      },
    );

    test('the empty definitions file remains valid Dart', () async {
      await definitions.writeAsString(generateSecretDefinitions([]));
      await probe.writeAsString(
        "import 'secrets.g.dart';\nvoid main() => print(Secrets);\n",
      );

      final result = await runProbe({});

      expect(result.exitCode, 0, reason: result.stderr.toString());
      expect(result.stdout, 'Secrets\n');
    });
  });
}
