version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/apps/dashboard"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/apps/openci_runner"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/openci_models"
    schedule:
      interval: "daily"
