version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/apps/cicd_sandbox_app"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "pub"
    directory: "/apps/dashboard"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "pub"
    directory: "/apps/openci_runner"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "pub"
    directory: "/packages/openci_models"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"