name: genuineci_api_client
description: Dart API client for the GenuineCI server.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  http: ^1.6.0
  serverpod_client: 4.0.0-rc.2
