analyzer:
  errors:
    file_names: ignore
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    unawaited_futures: true

formatter:
  trailing_commas: preserve

plugins:
  riverpod_lint: 3.1.4
