name: openci

packages:
  - apps/**
  - packages/**

scripts:
  ff:
    run: cd apps/firebase_functions && firebase deploy --only functions

  dashboard-runner:
    run: cd apps/dashboard && dart run build_runner watch -d
