name: openci
publish_to: none

environment:
  sdk: ^3.11.5

workspace:
  - apps/dashboard
  - apps/build_job_planner
  - apps/build_job_worker
  - apps/genuineci_cli
  - apps/genuineci_server
  - apps/openci_server
  - genuine_ci
  - packages/genuine_ci
  - packages/genuineci_api_client
  - packages/macos_updater
  - packages/openci_shared
  - packages/pubspec_version_hook

dependency_overrides:
  analyzer: 10.0.1
  dart_style: 3.1.7
