// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI (`genuineci sync paths`)
// dart format off

import 'package:genuine_ci/genuine_ci.dart' show WorkspaceDirectory;

/// Paths relative to the repository root.
abstract final class WorkspacePaths {
  static const root = WorkspaceRoot._('.');
}

extension type const WorkspaceRoot._(String _path) implements WorkspaceDirectory {
  WorkspaceRoot$Apps get apps => const WorkspaceRoot$Apps._("apps");
  WorkspaceDirectory get genuineCi => const WorkspaceDirectory("genuine_ci");
  WorkspaceRoot$Packages get packages => const WorkspaceRoot$Packages._("packages");
}

extension type const WorkspaceRoot$Apps._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get buildJobPlanner => const WorkspaceDirectory("apps/build_job_planner");
  WorkspaceDirectory get buildJobWorker => const WorkspaceDirectory("apps/build_job_worker");
  WorkspaceDirectory get dashboard => const WorkspaceDirectory("apps/dashboard");
  WorkspaceDirectory get genuineciCli => const WorkspaceDirectory("apps/genuineci_cli");
  WorkspaceDirectory get openciServer => const WorkspaceDirectory("apps/openci_server");
}

extension type const WorkspaceRoot$Packages._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get genuineCi => const WorkspaceDirectory("packages/genuine_ci");
  WorkspaceDirectory get macosUpdater => const WorkspaceDirectory("packages/macos_updater");
  WorkspaceDirectory get openciShared => const WorkspaceDirectory("packages/openci_shared");
  WorkspaceDirectory get pubspecVersionHook => const WorkspaceDirectory("packages/pubspec_version_hook");
}
