// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI (`genuineci sync paths`)
// dart format off

/// Paths relative to the repository root.
abstract final class WorkspacePaths {
  static const root = WorkspaceRoot._('.');
}

extension type const WorkspaceRoot._(String _path) implements String {
  WorkspaceRoot$Apps get apps => const WorkspaceRoot$Apps._("apps");
  String get genuineCi => "genuine_ci";
  WorkspaceRoot$Packages get packages => const WorkspaceRoot$Packages._("packages");
}

extension type const WorkspaceRoot$Apps._(String _path) implements String {
  String get buildJobPlanner => "apps/build_job_planner";
  String get buildJobWorker => "apps/build_job_worker";
  String get dashboard => "apps/dashboard";
  String get genuineciCli => "apps/genuineci_cli";
  String get openciServer => "apps/openci_server";
}

extension type const WorkspaceRoot$Packages._(String _path) implements String {
  String get genuineCi => "packages/genuine_ci";
  String get macosUpdater => "packages/macos_updater";
  String get openciShared => "packages/openci_shared";
  String get pubspecVersionHook => "packages/pubspec_version_hook";
}
