name: genuineci_server
description: GenuineCI server.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  serverpod: 4.0.0-rc.2

dev_dependencies:
  genuineci_api_client:
    path: ../../packages/genuineci_api_client
  test: ^1.31.0
