name: hk
description: A CLI app to translate text using Gemini.
version: 0.1.1
repository: https://github.com/open-ci-io/openci/tree/develop/apps/honyaku_konnyaku

environment:
  sdk: ^3.7.1

dependencies:
  args: ^2.6.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.15
