name: hk
description: A CLI app to translate text using ChatGPT.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  google_generative_ai: ^0.4.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
