name: hk
description: A CLI app to translate text using Gemini.
version: 0.0.1
repository: https://github.com/open-ci-io/openci/tree/develop/apps/honyaku_konnyaku

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.2
  google_generative_ai: ^0.4.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
