name: github_app
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  dart_firebase_admin: ^0.3.0
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^2.14.0
  dartssh2: ^2.8.2
  dotenv: ^4.2.0
  freezed_annotation: ^2.4.4
  github: ^9.24.0
  google_play_api_kit: ^0.2.6
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  json_annotation: ^4.9.0
  mason_logger: ^0.2.5
  openci_models:
    path: ../openci_models
  process_run: ^0.13.3
  pub_updater: ^0.3.0
  sentry: ^7.18.0
  uuid: ^4.2.1

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  build_version: ^2.1.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  melos: ^3.4.0
  mocktail: ^1.0.0
  pedantic_mono: ^1.29.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0
