name: vf
description: A dart bidings for Virtualization Framework from Apple.
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.6.0
  ffi: ^2.0.1
  objective_c: ^8.0.0

dev_dependencies:
  ffigen: ^19.0.0
  lints: ^5.0.0
  test: ^1.24.0
