import 'dart:convert';

import 'package:meta/meta.dart';
import 'package:path/path.dart' as p;

final _reservedFields =
    ('abstract as assert async augment await base break case catch class const '
            'continue covariant default deferred do dynamic else enum export extends '
            'extension external factory false final finally for Function get hide if '
            'implements import in interface is late library mixin native new null of on '
            'operator part required rethrow return sealed set show static super switch '
            'sync this throw true try type typedef var void when while with yield '
            'hashCode noSuchMethod runtimeType toString')
        .split(' ')
        .toSet();

/// Generates `WorkspacePaths` from package names and repository-relative paths.
String generateWorkspacePaths(Map<String, String> packages) {
  final names = packages.keys.toList()..sort();
  final fields = <String, String>{};
  for (final name in names) {
    final field = workspacePackageNameToField(name);
    final previous = fields[field];
    if (previous != null) {
      throw FormatException(
        'Packages ${jsonEncode(previous)} and ${jsonEncode(name)} '
        'both map to WorkspacePaths.$field. Rename one of them.',
      );
    }
    validateWorkspacePath(packages[name]!);
    fields[field] = name;
  }
  return generateWorkspacePathsSource({
    for (final entry in fields.entries) entry.key: packages[entry.value]!,
  });
}

@visibleForTesting
String workspacePackageNameToField(String name) {
  if (RegExp(r'[a-z][a-z0-9_]*').matchAsPrefix(name)?.end != name.length) {
    throw FormatException(
      'Invalid package name ${jsonEncode(name)}. '
      'Use lowercase letters, digits and underscores; start with a letter.',
    );
  }
  final words = name.split('_').where((word) => word.isNotEmpty).toList();
  final field =
      words.first +
      words
          .skip(1)
          .map((word) => word[0].toUpperCase() + word.substring(1))
          .join();
  if (_reservedFields.contains(field)) {
    throw FormatException(
      'Package ${jsonEncode(name)} cannot be used as a Dart field. '
      'Rename the package.',
    );
  }
  return field;
}

@visibleForTesting
void validateWorkspacePath(String path) {
  if (path.isEmpty ||
      p.posix.rootPrefix(path).isNotEmpty ||
      p.windows.rootPrefix(path).isNotEmpty ||
      RegExp(r'^[A-Za-z]:').hasMatch(path) ||
      path.split(RegExp(r'[/\\]')).contains('..') ||
      path.contains('\u0000')) {
    throw FormatException(
      'Invalid workspace path ${jsonEncode(path)}. '
      'Use a relative path within the repository without ".." or NUL.',
    );
  }
}

@visibleForTesting
String generateWorkspacePathsSource(Map<String, String> paths) {
  final buffer = StringBuffer('''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI
// dart format off

/// Paths relative to the repository root.
''');
  if (paths.isEmpty) {
    buffer.writeln('abstract final class WorkspacePaths {}');
  } else {
    buffer.writeln('abstract final class WorkspacePaths {');
    for (final entry in paths.entries) {
      final literal = jsonEncode(entry.value).replaceAll(r'$', r'\$');
      buffer.writeln('  static const String ${entry.key} = $literal;');
    }
    buffer.writeln('}');
  }
  return buffer.toString();
}
