import 'dart:convert';

import 'package:meta/meta.dart';
import 'package:path/path.dart' as p;

final _reservedFields =
    ('abstract as assert async augment await base break case catch class const '
            'continue covariant default deferred do dynamic else enum export extends '
            'extension external factory false final finally for Function get hide if '
            'implements import in interface is late library mixin native new null of on '
            'operator part required rethrow return sealed set show static super switch '
            'sync this throw true try type typedef var void when while with yield '
            'hashCode noSuchMethod runtimeType toString')
        .split(' ')
        .toSet();

/// Generates typed directory access from repository-relative workspace paths.
String generateWorkspacePaths(Iterable<String> paths) =>
    generateWorkspacePathsSource(buildWorkspacePathTree(paths));

class WorkspacePathNode {
  WorkspacePathNode(this.path, this.typeName);

  final String path;
  final String typeName;
  final children = <String, WorkspacePathNode>{};
}

@visibleForTesting
WorkspacePathNode buildWorkspacePathTree(Iterable<String> paths) {
  final normalized =
      paths
          .map((path) {
            validateWorkspacePath(path);
            return p.posix.normalize(path.replaceAll(r'\', '/'));
          })
          .toSet()
          .toList()
        ..sort();
  final root = WorkspacePathNode('.', 'WorkspaceRoot');
  for (final path in normalized) {
    var node = root;
    for (final segment in p.posix.split(path)) {
      if (segment == '.') continue;
      final field = workspaceDirectoryNameToField(segment);
      final childPath = node.path == '.' ? segment : '${node.path}/$segment';
      final previous = node.children[field];
      if (previous != null && previous.path != childPath) {
        throw FormatException(
          'Directories ${jsonEncode(previous.path)} and ${jsonEncode(childPath)} '
          'both map to "$field" under ${jsonEncode(node.path)}.',
        );
      }
      node = node.children.putIfAbsent(
        field,
        () => WorkspacePathNode(
          childPath,
          '${node.typeName}\$${field[0].toUpperCase()}${field.substring(1)}',
        ),
      );
    }
  }
  return root;
}

@visibleForTesting
String workspaceDirectoryNameToField(String name) {
  final words = name
      .replaceAllMapped(
        RegExp(r'([A-Z])([A-Z][a-z])'),
        (match) => '${match[1]}_${match[2]}',
      )
      .replaceAllMapped(
        RegExp(r'([a-z0-9])([A-Z])'),
        (match) => '${match[1]}_${match[2]}',
      )
      .split(RegExp(r'[^A-Za-z0-9]+'))
      .where((word) => word.isNotEmpty)
      .map((word) => word.toLowerCase())
      .toList();
  final field = words.isEmpty
      ? ''
      : words.first +
            words
                .skip(1)
                .map((word) => word[0].toUpperCase() + word.substring(1))
                .join();
  if (!RegExp(r'^[a-z]').hasMatch(field) || _reservedFields.contains(field)) {
    throw FormatException(
      'Directory ${jsonEncode(name)} cannot be used as a Dart field. '
      'Rename the directory.',
    );
  }
  return field;
}

void validateWorkspacePath(String path) {
  if (path.isEmpty ||
      p.posix.rootPrefix(path).isNotEmpty ||
      p.windows.rootPrefix(path).isNotEmpty ||
      RegExp(r'^[A-Za-z]:').hasMatch(path) ||
      path.split(RegExp(r'[/\\]')).contains('..') ||
      path.contains('\u0000')) {
    throw FormatException(
      'Invalid workspace path ${jsonEncode(path)}. '
      'Use a relative path within the repository without ".." or NUL.',
    );
  }
}

@visibleForTesting
String generateWorkspacePathsSource(WorkspacePathNode root) {
  final buffer = StringBuffer('''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI (`genuineci sync paths`)
// dart format off

/// Paths relative to the repository root.
abstract final class WorkspacePaths {
  static const root = WorkspaceRoot._('.');
}
''');
  _writeWorkspacePathNode(buffer, root);
  return buffer.toString();
}

void _writeWorkspacePathNode(StringBuffer buffer, WorkspacePathNode node) {
  buffer.writeln(
    '\nextension type const ${node.typeName}._(String _path) implements String {',
  );
  for (final entry in node.children.entries) {
    final child = entry.value;
    final literal = jsonEncode(child.path).replaceAll(r'$', r'\$');
    final type = child.children.isEmpty ? 'String' : child.typeName;
    final value = child.children.isEmpty
        ? literal
        : 'const ${child.typeName}._($literal)';
    buffer.writeln('  $type get ${entry.key} => $value;');
  }
  buffer.writeln('}');
  for (final child in node.children.values) {
    if (child.children.isNotEmpty) _writeWorkspacePathNode(buffer, child);
  }
}
