import 'dart:convert';

import 'package:meta/meta.dart';

final _reservedGetters =
    ('abstract as assert async augment await base break case catch class const '
            'continue covariant default deferred do dynamic else enum export extends '
            'extension external factory false final finally for Function get hide if '
            'implements import in interface is late library mixin native new null of on '
            'operator part required rethrow return sealed set show static super switch '
            'sync this throw true try type typedef var void when while with yield '
            'hashCode noSuchMethod runtimeType toString')
        .split(' ')
        .toSet();

String generateSecretDefinitions(Iterable<String> secretNames) {
  final names = secretNames.toSet().toList()..sort();
  final getters = <String, String>{};
  for (final name in names) {
    validateSecretName(name);
    final getter = secretNameToGetter(name);
    final previous = getters[getter];
    if (previous != null) {
      throw FormatException(
        'Secrets ${jsonEncode(previous)} and ${jsonEncode(name)} '
        'both map to Secrets.$getter. Rename one of them.',
      );
    }
    getters[getter] = name;
  }
  return generateSecretSource(getters);
}

@visibleForTesting
void validateSecretName(String name) {
  if (RegExp(r'[A-Za-z_][A-Za-z0-9_]*').matchAsPrefix(name)?.end !=
      name.length) {
    throw FormatException(
      'Invalid secret name ${jsonEncode(name)}. '
      'Use letters, digits and underscores; do not start with a digit.',
    );
  }
}

@visibleForTesting
String secretNameToGetter(String name) {
  final words = name
      .replaceAllMapped(
        RegExp(r'([A-Z])([A-Z][a-z])'),
        (match) => '${match[1]}_${match[2]}',
      )
      .replaceAllMapped(
        RegExp(r'([a-z0-9])([A-Z])'),
        (match) => '${match[1]}_${match[2]}',
      )
      .split('_')
      .where((word) => word.isNotEmpty)
      .map((word) => word.toLowerCase())
      .toList();
  final getter = words.isEmpty
      ? ''
      : words.first +
            words
                .skip(1)
                .map((word) => word[0].toUpperCase() + word.substring(1))
                .join();
  if (!RegExp(r'^[a-z]').hasMatch(getter) ||
      _reservedGetters.contains(getter)) {
    throw FormatException(
      'Secret ${jsonEncode(name)} cannot be used as a Dart getter. '
      'Rename the secret.',
    );
  }
  return getter;
}

@visibleForTesting
String generateSecretSource(Map<String, String> getters) {
  final buffer = StringBuffer('''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI (`genuineci sync secrets`)
// dart format off

''');
  if (getters.isNotEmpty) buffer.writeln("import 'dart:io';\n");
  buffer.writeln(
    '/// Provides type-safe access to Genuine CI secrets via environment variables.',
  );
  if (getters.isEmpty) {
    buffer.writeln('abstract final class Secrets {}');
  } else {
    buffer.writeln('abstract final class Secrets {');
    buffer.write(
      getters.entries
          .map(
            (entry) =>
                '''
  /// Secret key: `${entry.value}`
  static String get ${entry.key} =>
      Platform.environment['${entry.value}'] ??
      (throw StateError("Secret '${entry.value}' is not set in environment."));
''',
          )
          .join('\n'),
    );
    buffer.writeln('}');
  }
  return buffer.toString();
}
