name: openci_cli2
description: OpenCI CLI
version: 0.1.8
repository: https://github.com/open-ci-io/openci/tree/develop/apps/openci_cli
homepage: https://open-ci.io

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  dart_jsonwebtoken: ^3.2.0
  http: ^1.4.0
  mason_logger: ^0.3.3
  openci_models: ^1.3.3
  path: ^1.9.1
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.5.0
  build_verify: ^3.1.1
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^7.0.0

executables:
  ? openci_cli2
