name: openci_cli
description: OpenCI CLI
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  dart_jsonwebtoken: ^2.16.0
  http: ^1.3.0
  mason_logger: ^0.3.0
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  openci_cli:
