name: macos_updater
description: "A macOS-only Flutter plugin for Sparkle-based app updates."
version: 0.0.1
homepage: https://github.com/openci-org/openci

environment:
  sdk: ^3.11.5
  flutter: ">=3.41.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.0.1

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: MacosUpdaterPlugin
