name: build_job_executor
description: OpenCIのビルドジョブを実行するプログラム。
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  http: ^1.2.0
  logging: ^1.2.0
  openci_shared: ^1.0.1
  retry: ^3.1.2
  sentry: ^9.22.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
