[package]
name = "openci_worker"
version = "0.1.0"
edition = "2021"
authors = ["OpenCI <m.aoki@openci.com>"]
description = "OpenCI Worker CLI"
license = "MIT"

[[bin]]
name = "openci-worker"
path = "src/main.rs"

[dependencies]