DROP TRIGGER IF EXISTS update_repositories_updated_at ON repositories;
DROP TRIGGER IF EXISTS update_workflows_updated_at ON workflows;
DROP TRIGGER IF EXISTS update_secrets_updated_at ON secrets;
DROP FUNCTION IF EXISTS update_updated_at_column();
DROP TABLE IF EXISTS secrets;
DROP TABLE IF EXISTS github_events;
DROP TABLE IF EXISTS command_logs;
DROP TABLE IF EXISTS build_jobs;
DROP TABLE IF EXISTS workflows;
DROP TABLE IF EXISTS repositories;